<?php

namespace Database\Seeders;

use App\Models\Member;
use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["name" => "Lita", "address" => "E15/9"],
            ["name" => "Jenny", "address" => "E1/3"],
            ["name" => "Ambarwati", "address" => "E3/"],
            ["name" => "Fifi", "address" => "E2/2"],
            ["name" => "Fathimah", "address" => "E8/20"],
            ["name" => "Ariati", "address" => "E16/3"],
            ["name" => "Yuli", "address" => "E15/25"],
            ["name" => "Sri Gatot", "address" => "E1/19"],
            ["name" => "Nina", "address" => "E16/7"],
            ["name" => "Tuty", "address" => "E8/39"],
            ["name" => "Uke", "address" => "E11/18"],
            ["name" => "Genny", "address" => "E10/21"],
            ["name" => "Ninik", "address" => "E16/11"],
            ["name" => "Ruby", "address" => "E16/1"],
            ["name" => "Carla", "address" => "E12/15"],
            ["name" => "Elvita", "address" => "E6/3"],
            ["name" => "Anik", "address" => "E2"],
            ["name" => "Intan", "address" => "E16/2"],
            ["name" => "Tini", "address" => "E8/18"],
            ["name" => "Ratri", "address" => "E16/6"],
            ["name" => "Sodaqo", "address" => "CW"],
            ["name" => "Bambang/Mega", "address" => "E11/11"],
            ["name" => "Juli", "address" => "E10/6"],
            ["name" => "Ibu Lis", "address" => "E8/38"],
            ["name" => "Winda", "address" => "E12/10"],
            ["name" => "Mala", "address" => "E11/26"],
            ["name" => "Krismanto", "address" => "E23-25"],
            ["name" => "Neneng", "address" => "E12/11"],
            ["name" => "Diah Bulani", "address" => "E17/20"],
            ["name" => "Esti", "address" => null],
            ["name" => "Wida", "address" => "E11/12"],
            ["name" => "Noemi", "address" => "Blok E18/"],
            ["name" => "Lisa", "address" => "E1"],
            ["name" => "Fanny", "address" => null],
            ["name" => "Rini", "address" => null],
            ["name" => "Dina Didik", "address" => null],
            ["name" => "Nani Syahnan", "address" => null],
            ["name" => "Ratna Giri", "address" => "E1/10"],
            ["name" => "Nurmala Setiawan", "address" => null],
            ["name" => "Amelia", "address" => "AA/Aversa"],
            ["name" => "Lima Londry/ Lita", "address" => null],
            ["name" => "Lani", "address" => "E7/32"],
            ["name" => "Demak", "address" => "E16"],
            ["name" => "Yohana", "address" => null],
            ["name" => "Melisa", "address" => "G9/12"],
            ["name" => "Tantie", "address" => "AA 12/6"],
            ["name" => "Vita", "address" => "E8/37"],
            ["name" => "Nadia", "address" => "J10/5"],
            ["name" => "Dyah", "address" => "E12/21"],
            ["name" => "Desy", "address" => "Rafles"],
            ["name" => "Karim Yus", "address" => "E15/17"],
            ["name" => "Wahyo", "address" => null],
            ["name" => "RT 3 Blok E", "address" => null],
            ["name" => "Hestu", "address" => "Blok S"],
            ["name" => "Tk. Ibnul Baladi", "address" => null],
            ["name" => "Eri", "address" => null],
            ["name" => "Ardison", "address" => "E11/23"],
            ["name" => "Yenny", "address" => "K2/8"],
            ["name" => "Woro", "address" => null],
            ["name" => "Upik/An", "address" => "E5/9"],
            ["name" => "Ruth", "address" => null],
            ["name" => "Anne", "address" => null],
            ["name" => "Mila", "address" => "G17/18"],
            ["name" => "Santi", "address" => "J8/8"],
            ["name" => "Indri", "address" => null],
            ["name" => "Engkus", "address" => null],
            ["name" => "Puput", "address" => null],
            ["name" => "Loli", "address" => "K5/16"],
            ["name" => "Savitri/Pipit", "address" => "blok C"],
            ["name" => "Danty", "address" => null],
            ["name" => "Ata /bu Irin", "address" => "Address"],
            ["name" => "Aya /bu Irin", "address" => "B8/81"],
            ["name" => "Agus", "address" => null],
            ["name" => "Sri Kamistan", "address" => "E17/3"],
            ["name" => "Keisha", "address" => null],
            ["name" => "Isti", "address" => "E7"],
            ["name" => "Titin", "address" => "K7/29"],
            ["name" => "Retno", "address" => "K2/35"],
            ["name" => "Rima", "address" => "BB7/36"],
            ["name" => "Inni", "address" => "S2/51"],
            ["name" => "Siska", "address" => "S8"],
            ["name" => "Pia", "address" => "i1/21"],
            ["name" => "Iin Khafid", "address" => "E?"],
            ["name" => "Yuni", "address" => "AA15/55"],
            ["name" => "Lollyta", "address" => "i8/70"],
            ["name" => "Reni", "address" => "AA15"],
            ["name" => "Adviyany", "address" => null],
            ["name" => "Wanty", "address" => null],
            ["name" => "Nur", "address" => "N8"],
        ];

        Member::insert($data);
    }
}
